
#define DEF_FDD_OK		0
#define DEF_FDD_ERROR	-1

typedef enum {
	FDC_COMMAND_READ_TRACK				= 0x02,
	FDC_COMMAND_SPECIFY					= 0x03,
	FDC_COMMAND_SENSE_DRIVE_STATUS		= 0x04,
	FDC_COMMAND_WRITE_DATA				= 0x05,
	FDC_COMMAND_READ_DATA				= 0x06,
	FDC_COMMAND_RECALIBRATE				= 0x07,
	FDC_COMMAND_SENSE_INTERRUPT_STAUS	= 0x08,
	FDC_COMMAND_WRITE_DELETED_DATA		= 0x09,
	FDC_COMMAND_READ_ID					= 0x0a,
	FDC_COMMAND_READ_DELETED_DATA		= 0x0c,
	FDC_COMMAND_FORMAT_TRACK			= 0x0d,
	FDC_COMMAND_DUMPREG					= 0x0e,
	FDC_COMMAND_SEEK					= 0x0f,
	FDC_COMMAND_VERSION					= 0x10,
	FDC_COMMAND_SCAN_EQUAL				= 0x11,
	FDC_COMMAND_PERPENDICULAR_MODE		= 0x12,
	FDC_COMMAND_CONFIGURE				= 0x13,
	FDC_COMMAND_LOCK					= 0x14,
	FDC_COMMAND_VERIFY					= 0x16,
	FDC_COMMAND_SCAN_LOW_OR_EQUAL		= 0x19,
	FDC_COMMAND_SCAN_HIGH_OR_EQUAL		= 0x1d,
	FDC_COMMAND_RELATIVE_SEEK			= 0x8f
} E_FDC_COMMAND;
